### ISSUE TITLE
TypeError: Accounts.findUserByUsername is not a function

### ISSUE THREAD

**Issue by YstFA** [meteor/vue-tutorial#16]
Getting this Error when downloading step 11 or step 12 after running "meteor npm install" and "meteor"

```
TypeError: Accounts.findUserByUsername is not a function
  at server/main.js:18:17
  at Function.time (/Users/Shared/DEV/meteor/.meteor/local/build/programs/server/profile.js:273:30)
  at /Users/Shared/DEV/meteor/.meteor/local/build/programs/server/boot.js:415:15
  at /Users/Shared/DEV/meteor/.meteor/local/build/programs/server/boot.js:465:7
  at Function.run (/Users/Shared/DEV/meteor/.meteor/local/build/programs/server/profile.js:280:14)
  at /Users/Shared/DEV/meteor/.meteor/local/build/programs/server/boot.js:463:13
```

**Comment by Grubba27** [comment]
Hello there! how are you doing?
Wich version of meteor are you using ?
Does this happen when you use this folder from the repo?  [step11](https://github.com/meteor/vue-tutorial/tree/master/src/simple-todos/step11).
Tried in my machine running the same commands  ``meteor npm i``  then ``meteor`` and it did compile.
 Can you provide more info?
